git:
  branchLogCmd: git lg
  paging:
    colorArg: always
    pager: delta --paging=never --light -s
customCommands:
  - key: "<C-t>"
    context: "localBranches"
    description: "Checkout trunk branch"
    command: "git cotrunk"
