"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$cmd_duration\
$rust\
$nodejs\
$battery\
$line_break\
$character
"""

[battery]
format = '[\[$symbol$percentage\]]($style)'

[[battery.display]]
threshold = 100

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red) '

[cmd_duration]
min_time = 5000

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style)"

[git_status]
format = "([$all_status$ahead_behind]($style))"

[nodejs]
symbol = " "
format = '[\[$symbol($version)\]]($style)'
version_format = "${raw}"

[rust]
format = '[\[$symbol($version)\]]($style)'
version_format = "${raw}"

